# Generated by Django 5.2.12 on 2026-08-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('operaciones', '0004_historicalincident_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='numero_relacion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbillingrecord',
            name='numero_relacion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalclientpayment',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='billingrecord',
            unique_together={('operation', 'numero_relacion')},
        ),
    ]
