# Generated by Django 5.2.12 on 2026-08-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_billingrecord_numero_relacion_clientpayment_metodo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billingrecord',
            unique_together=set(),
        ),
    ]
