# Generated by Django 5.2.12 on 2026-08-17 12:18

from django.db import migrations


def backfill_numero_relacion(apps, schema_editor):
    BillingRecord = apps.get_model("facturacion", "BillingRecord")
    Operation = apps.get_model("operaciones", "Operation")
    brs = BillingRecord.objects.exclude(
        numero_relacion__isnull=False
    ).exclude(numero_relacion="")
    for op_id in brs.values_list("operation_id", flat=True).distinct():
        codigo = Operation.objects.get(pk=op_id).codigo
        prefix = f"REL-{codigo}-"
        secuencia = 0
        records = BillingRecord.objects.filter(
            operation_id=op_id
        ).order_by("fecha", "shift__fecha_inicio")
        for br in records:
            if br.numero_relacion:
                continue
            secuencia += 1
            br.numero_relacion = f"{prefix}{secuencia:03d}"
            br.save(update_fields=["numero_relacion"])


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_billingrecord_unique_together'),
    ]

    operations = [
        migrations.RunPython(backfill_numero_relacion, migrations.RunPython.noop),
    ]