# Generated by Django 5.2.12 on 2026-08-16 00:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_rename_client_cargogenerator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOperation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('buque', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('meta_horas', models.DecimalField(decimal_places=1, default=11, max_digits=4)),
                ('tarifa_hora', models.DecimalField(decimal_places=0, max_digits=14)),
                ('valor_turno_dia', models.DecimalField(decimal_places=0, max_digits=14)),
                ('valor_turno_noche', models.DecimalField(decimal_places=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generador_de_carga', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogos.cargogenerator')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('puerto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogos.port')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Operación',
                'verbose_name_plural': 'historical Operaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('buque', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('meta_horas', models.DecimalField(decimal_places=1, default=11, max_digits=4)),
                ('tarifa_hora', models.DecimalField(decimal_places=0, max_digits=14)),
                ('valor_turno_dia', models.DecimalField(decimal_places=0, max_digits=14)),
                ('valor_turno_noche', models.DecimalField(decimal_places=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generador_de_carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='catalogos.cargogenerator')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='catalogos.port')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['fecha_inicio', 'codigo'],
            },
        ),
    ]
