# Generated by Django 5.2.12 on 2026-08-16 00:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
        ('flota', '0001_initial'),
        ('operaciones', '0002_historicaloperationvehicle_operationvehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalShift',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('meta_horas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cumplimiento_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('tipo', models.CharField(choices=[('dia', 'Día'), ('noche', 'Noche')], max_length=10)),
                ('valor_estandar', models.DecimalField(decimal_places=0, max_digits=14)),
                ('valor_pagado', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado'), ('anulado', 'Anulado')], default='programado', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='conductores.driver')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operaciones.operation')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flota.vehicle')),
            ],
            options={
                'verbose_name': 'historical Turno',
                'verbose_name_plural': 'historical Turnos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('meta_horas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cumplimiento_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('tipo', models.CharField(choices=[('dia', 'Día'), ('noche', 'Noche')], max_length=10)),
                ('valor_estandar', models.DecimalField(decimal_places=0, max_digits=14)),
                ('valor_pagado', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado'), ('anulado', 'Anulado')], default='programado', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='conductores.driver')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='operaciones.operation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='flota.vehicle')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
