# Generated by Django 5.2.12 on 2026-09-14 14:23

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_historicalproveedor_proveedor'),
        ('flota', '0001_initial'),
        ('operaciones', '0005_historicalshiftstop_shiftstop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOperationExpense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('categoria', models.CharField(choices=[('combustible', 'Combustible / ACPM'), ('repuesto', 'Repuesto'), ('llanta', 'Llanta / Llantería'), ('mantenimiento', 'Mantenimiento'), ('mano_obra', 'Mano de obra'), ('peaje', 'Peaje'), ('lavado', 'Lavado'), ('otros', 'Otros')], max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=14)),
                ('galones', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('numero_factura', models.CharField(blank=True, default='', max_length=50)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operaciones.operation')),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogos.proveedor')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flota.vehicle')),
            ],
            options={
                'verbose_name': 'historical Gasto de operación',
                'verbose_name_plural': 'historical Gastos de operación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OperationExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('combustible', 'Combustible / ACPM'), ('repuesto', 'Repuesto'), ('llanta', 'Llanta / Llantería'), ('mantenimiento', 'Mantenimiento'), ('mano_obra', 'Mano de obra'), ('peaje', 'Peaje'), ('lavado', 'Lavado'), ('otros', 'Otros')], max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=14)),
                ('galones', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('numero_factura', models.CharField(blank=True, default='', max_length=50)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='operaciones.operation')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='catalogos.proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_expenses', to='flota.vehicle')),
            ],
            options={
                'verbose_name': 'Gasto de operación',
                'verbose_name_plural': 'Gastos de operación',
                'ordering': ['-fecha'],
            },
        ),
    ]
