# Generated by Django 5.2.12 on 2026-08-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_driveradvance_historicaldriveradvance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveradvance',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='driveradvance',
            name='tipo',
            field=models.CharField(choices=[('adelanto', 'Adelanto'), ('pago', 'Pago')], default='adelanto', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldriveradvance',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldriveradvance',
            name='tipo',
            field=models.CharField(choices=[('adelanto', 'Adelanto'), ('pago', 'Pago')], default='adelanto', max_length=20),
        ),
    ]
