# Generated by Django 5.2.12 on 2026-08-16 21:18

from django.db import migrations, models


def _recalcular_fifo_fecha(apps, schema_editor):
    PayrollItem = apps.get_model("nomina", "PayrollItem")
    DriverAdvance = apps.get_model("nomina", "DriverAdvance")
    Driver = apps.get_model("conductores", "Driver")
    for driver in Driver.objects.all():
        items = list(
            PayrollItem.objects.filter(shift__driver=driver)
            .select_related("shift", "payroll")
            .order_by(
                "payroll__periodo_inicio",
                "payroll__periodo_fin",
                "shift__fecha_inicio",
                "shift__fecha_fin",
                "id",
            )
        )
        advances = list(
            DriverAdvance.objects.filter(driver=driver).order_by("fecha", "id")
        )
        disponible = sum((a.valor for a in advances), start=0)
        for item in items:
            pagado = min(item.valor, disponible) if disponible > 0 else 0
            if item.pagado != pagado:
                item.pagado = pagado
                item.save(update_fields=["pagado"])
            disponible -= pagado


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_driveradvance_metodo_driveradvance_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayrollitem',
            name='pagado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='pagado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.RunPython(_recalcular_fifo_fecha, migrations.RunPython.noop),
    ]
