# Generated by Django 5.2.12 on 2026-08-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="CargoGenerator",
        ),
        migrations.AlterModelOptions(
            name="cargogenerator",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Generador de carga",
                "verbose_name_plural": "Generadores de carga",
            },
        ),
        migrations.AlterField(
            model_name="cargogenerator",
            name="nit",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="NIT"
            ),
        ),
        migrations.RenameModel(
            old_name="HistoricalClient",
            new_name="HistoricalCargoGenerator",
        ),
        migrations.AlterModelOptions(
            name="historicalcargogenerator",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Generador de carga",
                "verbose_name_plural": "historical Generadores de carga",
            },
        ),
        migrations.AlterField(
            model_name="historicalcargogenerator",
            name="nit",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, verbose_name="NIT"
            ),
        ),
    ]
